name = "scholar-stats"
main = "scholar-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "scholar-stats"
routes = [
  { pattern = "scholar-stats.YOUR_SUBDOMAIN.workers.dev", zone_name = "YOUR_DOMAIN.com" }
]
